### ISSUE TITLE
init_tinymce_hammer_if_required does nothing

### ISSUE THREAD

**Issue by fjyaniez** [trevorrowe/tinymce_hammer#6]
Installed from trevorrowe-tinymce_hammer-c3ffc5395c8b07ccbe4d91dd2d4012d9344f3a9f.tar,

when I call init_tinymce_hammer_if_required, it does nothing. Nothing is added to the page source, so tinymce helpers doesn't work.

**Comment by trevorrowe** [comment]
The helper method init_tinymce_hammer_if_required return a pair of script tags, but only if required by a helper on the page. Calling tinymce_tag, tinymce or FormBuilder#tinymce will all prompt the script tags to appear.

Please let me know if this doesn't solve your issue and you continue to have issues.

**Comment by fjyaniez** [comment]
Hi!

The problem was I called init_tinymce_hammer_if_required in a content_for block. When I put the method call directly in the header, it worked. 

Why it can't work in this piece of code?

yield :head

content_for :head do
   init_tinymce_hammer_if_required
end

**Comment by trevorrowe** [comment]
That makes sense.  

init_tinymce_hammer_if_required mnethod is very simple.  If @tinymce_hammer_required is true it calls another method, tinymce_hammer_javascript_tags.  The @tinymce_hammer_required instance variable it set to true by any of the view helpers (tinymce_tag, tinymce and FormBuilder#tinymce).  I believe the issue is that content_for executes right away, instead of after the rendering of all nested partials.  

A simple fix would be to replace "init_tinymce_hammer_if_required" with "tinymce_hammer_javascript_tags".  The second method will always insert the javascript tags into the head, whether inside the content_for or not.  The biggest drawback is that you will force your users to load tinymce on every page.  The javascript will cache and so this usually isn't that big of an issue, but its something to consider.

To be honest, I am not sure how to resolve the issue with content_for.  Its the same reason why content_for is not compatible with partial caching.

**Comment by trevorrowe** [comment]
I had one more idea.  You could continue using the init_tinymce_hammer_if_required method if you call require_tinymce_hammer from the controllers / actions that require tinymce.  This solves the issue because the controller will set @require_tinymce_hammer to true before the view render gets to your content_for block.  Just add something like:

   before_filter :require_tinymce_hammer

to any of your controllers.  Feel free to add :only => .. or :except => .. options to limit which pages tinymce is required on.  Its not ideal, but it is better than loading tinymce on every page.

**Comment by trevorrowe** [comment]
I'm assuming this has resolved your issue, please let me know if it hasn't.
